{
    "KPlugin": {
        "Description": "Archive Handling Tool",
        "Description[ca@valencia]": "Eina de gestió d'arxius",
        "Description[ca]": "Eina de gestió d'arxius",
        "Description[eo]": "Arkivpritrakta Ilo",
        "Description[es]": "Herramienta de gestión de archivos comprimidos",
        "Description[eu]": "Artxiboak kudeatzeko tresna",
        "Description[ia]": "Instrumento de manear archivo",
        "Description[it]": "Strumento di gestione degli archivi",
        "Description[ka]": "არქივებთან სამუშაო ხელსაწყო",
        "Description[ko]": "압축 파일 처리 도구",
        "Description[nl]": "Hulpprogramma voor het beheren van archieven",
        "Description[nn]": "Verktøy for arkivhandsaming",
        "Description[pt]": "Ferramenta de Tratamento de Pacotes",
        "Description[pt_BR]": "Ferramenta de manipulação de arquivos",
        "Description[sl]": "Orodje za upravljanje arhivov",
        "Description[tr]": "Arşiv İşleme Aracı",
        "Description[uk]": "Інструмент для роботи з архівами",
        "Description[x-test]": "xxArchive Handling Toolxx",
        "Description[zh_CN]": "压缩文件管理工具",
        "Icon": "ark",
        "License": "GPL v2+",
        "MimeTypes": [
            "@SUPPORTED_ARK_MIMETYPES_JSON@"
        ],
        "Name": "Archiver",
        "Name[ca@valencia]": "Arxivador",
        "Name[ca]": "Arxivador",
        "Name[eo]": "Arkivilo",
        "Name[es]": "Archivador",
        "Name[eu]": "Artxibatzailea",
        "Name[ia]": "Archivaor",
        "Name[it]": "Utilità di archiviazione",
        "Name[ka]": "არქივატორი",
        "Name[ko]": "압축 도구",
        "Name[nl]": "Archiefgereedschap",
        "Name[nn]": "Arkivprogram",
        "Name[pt]": "Ark",
        "Name[pt_BR]": "Arquivador",
        "Name[ru]": "Архиватор",
        "Name[sl]": "Arhivar",
        "Name[ta]": "காப்பக உருவாக்கி",
        "Name[tr]": "Arşivleyici",
        "Name[uk]": "Архіватор",
        "Name[x-test]": "xxArchiverxx",
        "Name[zh_CN]": "压缩文件管理工具",
        "ServiceTypes": [
            "KParts/ReadOnlyPart",
            "Browser/View"
        ],
        "Version": "@ARK_VERSION@",
        "Website": "https://utils.kde.org/projects/ark"
    }
}
