{
    "KPlugin": {
        "Description": "Archive Handling Tool",
        "Description[af]": "Argief Handtering Program",
        "Description[ar]": "أداة التعامل مع الملفات المضغوطة",
        "Description[ast]": "Ferramienta pa remanar archivos",
        "Description[az]": "Arxiv İdarəetmə Aləti",
        "Description[be]": "Інструмент для апрацоўвання архіваў",
        "Description[bg]": "Инструмент за обработка на архиви",
        "Description[br]": "Ostilh merañ an dielloù",
        "Description[bs]": "Alatka za rukovanje arhivama",
        "Description[ca@valencia]": "Eina per a treballar amb arxius",
        "Description[ca]": "Eina per a treballar amb arxius",
        "Description[cs]": "Program pro práci s archivy",
        "Description[cy]": "Erfyn Triniaeth Archif",
        "Description[da]": "Arkivbehandlingsværktøj",
        "Description[de]": "Archiv-Verwaltung",
        "Description[el]": "Εργαλείο χειρισμού αρχειοθηκών",
        "Description[en_GB]": "Archive Handling Tool",
        "Description[eo]": "Administrilo por arĥivoj",
        "Description[es]": "Herramienta de gestión de archivos",
        "Description[et]": "Arhiivide haldamise rakendus",
        "Description[eu]": "Artxiboak kudeatzeko tresna",
        "Description[fa]": "ابزار گرداندن بایگانی",
        "Description[fi]": "Pakkausohjelma",
        "Description[fr]": "Outil de manipulation d'archives",
        "Description[ga]": "Uirlis Láimhseála Cartlainne",
        "Description[gl]": "Utilidade de manexo de arquivos",
        "Description[he]": "כלי לניהול ארכיונים",
        "Description[hne]": "अभिलेख संभाल औजार",
        "Description[hr]": "Uslužni program za arhiviranje",
        "Description[hu]": "Tömörítőprogram",
        "Description[ia]": "Instrumento de manear archivo",
        "Description[id]": "Alat Penanganan Arsip",
        "Description[ie]": "Gerente de archives",
        "Description[is]": "Vinna með safnskrár",
        "Description[it]": "Gestione degli archivi",
        "Description[ja]": "アーカイブを操作するツール",
        "Description[ka]": "არქივებთან სამუშაო ხელსაწყო",
        "Description[kk]": "Архивпен айналысу құралы",
        "Description[km]": "ឧបករណ៍​គ្រប់គ្រង​ប័ណ្ណសារ",
        "Description[ko]": "압축 파일 도구",
        "Description[lt]": "Archyvų apdorojimo įrankis",
        "Description[lv]": "Arhīvu apstrādes rīks",
        "Description[mk]": "Алатка за справување со архивирани датотеки",
        "Description[mr]": "संग्रह हाताळणारे साधन",
        "Description[ms]": "Alatan Pengendalian Arkib",
        "Description[nb]": "Arkivbehandlingsverktøy",
        "Description[nds]": "En Warktüüch för de Archievpleeg",
        "Description[ne]": "ह्यान्डलिङ उपकरण सङ्ग्रह गर्नुहोस्",
        "Description[nl]": "Hulpprogramma voor het beheren van archieven",
        "Description[nn]": "Verktøy for arkivhandsaming",
        "Description[pa]": "ਅਕਾਇਵ ਹੈਡਲਿੰਗ ਟੂਲ",
        "Description[pl]": "Program obsługi archiwów",
        "Description[pt]": "Programa de gestão de arquivos",
        "Description[pt_BR]": "Ferramenta de manipulação de arquivos",
        "Description[ro]": "Utilitar de manipulare arhive",
        "Description[ru]": "Программа работы с архивами",
        "Description[sk]": "Nástroj na prácu s archívmi",
        "Description[sl]": "Orodje za ravnanje z arhivi",
        "Description[sq]": "Vegël për paketimin e skedave",
        "Description[sr@ijekavian]": "Алатка за руковање архивама",
        "Description[sr@ijekavianlatin]": "Alatka za rukovanje arhivama",
        "Description[sr@latin]": "Alatka za rukovanje arhivama",
        "Description[sr]": "Алатка за руковање архивама",
        "Description[sv]": "Verktyg för att hantera filarkiv",
        "Description[ta]": "காப்பகத்தை கையாளும் கருவி",
        "Description[tg]": "Асбобҳои Дасткории Бойгонӣ",
        "Description[th]": "เครื่องมือจัดการแฟ้มจัดเก็บ",
        "Description[tr]": "Arşiv İşleme Aracı",
        "Description[uk]": "Засіб роботи з архівами",
        "Description[uz@cyrillic]": "Архив учун восита",
        "Description[uz]": "Arxiv uchun vosita",
        "Description[vi]": "Công Cụ Xử Lí Các Tệp Nén",
        "Description[wa]": "Usteye po-z apougnî les årtchives",
        "Description[x-test]": "xxArchive Handling Toolxx",
        "Description[xh]": "Isixhobo sokuphatha i Archive",
        "Description[zh_CN]": "压缩包文件管理工具",
        "Description[zh_TW]": "壓縮檔處理工具",
        "Icon": "ark",
        "License": "GPL v2+",
        "MimeTypes": ["@SUPPORTED_ARK_MIMETYPES_JSON@"],
        "Name": "Archiver",
        "Name[af]": "Argifeerder",
        "Name[ar]": "المؤرشف",
        "Name[ast]": "Archivador",
        "Name[az]": "Arxivləyici",
        "Name[be]": "Архіватар",
        "Name[bg]": "Архиватор",
        "Name[br]": "Dieller",
        "Name[bs]": "Arhivar",
        "Name[ca@valencia]": "Arxivador",
        "Name[ca]": "Arxivador",
        "Name[cs]": "Archivátor",
        "Name[cy]": "Archifydd",
        "Name[da]": "Arkivbehandler",
        "Name[de]": "Archivprogramm",
        "Name[el]": "Πρόγραμμα αρχειοθέτησης",
        "Name[en_GB]": "Archiver",
        "Name[eo]": "Arkivilo",
        "Name[es]": "Archivador",
        "Name[et]": "Arhiveerija",
        "Name[eu]": "Artxibatzeko programa",
        "Name[fa]": "بایگانی‌کننده",
        "Name[fi]": "Pakkausohjelma",
        "Name[fr]": "Archiveur",
        "Name[ga]": "Archiver",
        "Name[gl]": "Arquivador",
        "Name[he]": "מנהל הארכיונים",
        "Name[hne]": "अभिलेखक",
        "Name[hr]": "Arhiver",
        "Name[hu]": "Ark fájltömörítő",
        "Name[ia]": "Archivator",
        "Name[id]": "Pengarsip",
        "Name[ie]": "Archivator",
        "Name[is]": "Skráasafnari",
        "Name[it]": "Utilità di archiviazione",
        "Name[ja]": "アーカイバ",
        "Name[ka]": "არქივატორი",
        "Name[kk]": "Архивтегіш",
        "Name[km]": "កម្មវិធីប័ណ្ណសារ",
        "Name[ko]": "Archiver",
        "Name[lt]": "Archyvavimo programa",
        "Name[lv]": "Arhivātors",
        "Name[mk]": "Архивер",
        "Name[mr]": "संग्रहकर्ता",
        "Name[ms]": "Pengarkib",
        "Name[nb]": "Arkivbehandler",
        "Name[nds]": "Archivater",
        "Name[ne]": "सङ्ग्रहक",
        "Name[nl]": "Archiefgereedschap",
        "Name[nn]": "Arkivprogram",
        "Name[pa]": "ਅਕਾਇਵਰ",
        "Name[pl]": "Ark",
        "Name[pt]": "Ark",
        "Name[pt_BR]": "Arquivador",
        "Name[ro]": "Arhivator",
        "Name[ru]": "Архиватор",
        "Name[sk]": "Archivačný nástroj",
        "Name[sl]": "Pakirnik",
        "Name[sq]": "Paketues",
        "Name[sr@ijekavian]": "Архивар",
        "Name[sr@ijekavianlatin]": "Arhivar",
        "Name[sr@latin]": "Arhivar",
        "Name[sr]": "Архивар",
        "Name[sv]": "Arkiverare",
        "Name[ta]": "காப்பகம் உருவாக்கி",
        "Name[tg]": "Бойгонигар",
        "Name[th]": "ตัวสร้างแฟ้มจัดเก็บ",
        "Name[tr]": "Arşivleyici",
        "Name[uk]": "Архіватор",
        "Name[uz@cyrillic]": "Архивлагич",
        "Name[uz]": "Arxivlagich",
        "Name[vi]": "Trình Lưu Trữ",
        "Name[wa]": "Årtchiveu",
        "Name[x-test]": "xxArchiverxx",
        "Name[xh]": "Umenzi woshicilelo lukawonke-wonke noxwebhu lweMbali",
        "Name[zh_CN]": "压缩/解压工具",
        "Name[zh_TW]": "壓縮檔處理器",
        "ServiceTypes": [
            "KParts/ReadOnlyPart",
            "Browser/View"
        ],
        "Version": "@ARK_VERSION@",
        "Website": "https://utils.kde.org/projects/ark"
    }
}
