/*
 * This file was generated by dbusxml2cpp version 0.6
 * Command line was: dbusxml2cpp -v dnddbusinterface.xml -a dnddbusinterface
 *
 * dbusxml2cpp is Copyright (C) 2006 Trolltech ASA. All rights reserved.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "dnddbusinterface.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class DndExtractAdaptor
 */

DndExtractAdaptor::DndExtractAdaptor(QObject *parent)
        : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

DndExtractAdaptor::~DndExtractAdaptor()
{
    // destructor
}

void DndExtractAdaptor::extractSelectedFilesTo(const QString &path)
{
    // handle method call org.kde.DndExtract.extractSelectedFilesTo
    QMetaObject::invokeMethod(parent(), "extractSelectedFilesTo", Q_ARG(QString, path));
}

