/*
 * This file was generated by dbusxml2cpp version 0.6
 * Command line was: dbusxml2cpp -v dnddbusinterface.xml -a dnddbusinterface
 *
 * dbusxml2cpp is Copyright (C) 2006 Trolltech ASA. All rights reserved.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef DNDDBUSINTERFACE_H_1217639736
#define DNDDBUSINTERFACE_H_1217639736

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;

/*
 * Adaptor class for interface org.kde.DndExtract
 */
class DndExtractAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.kde.DndExtract")
    Q_CLASSINFO("D-Bus Introspection", ""
                "  <interface name=\"org.kde.DndExtract\" >\n"
                "    <method name=\"extractSelectedFilesTo\" >\n"
                "      <arg direction=\"in\" type=\"s\" name=\"path\" />\n"
                "    </method>\n"
                "  </interface>\n"
                "")
public:
    DndExtractAdaptor(QObject *parent);
    virtual ~DndExtractAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void extractSelectedFilesTo(const QString &path);
Q_SIGNALS: // SIGNALS
};

#endif
