[Desktop Entry]
Type=Service
X-KDE-ServiceTypes=Kerfuffle/Plugin
X-KDE-Library=kerfuffle_clilha
X-KDE-PluginInfo-Author=Theofilos Intzoglou
X-KDE-PluginInfo-Email=int.teo@gmail.com
X-KDE-PluginInfo-Name=kerfuffle_clilha
X-KDE-PluginInfo-Version=0.0.1
X-KDE-PluginInfo-Website=http://www.kde.org
X-KDE-PluginInfo-License=GPLv2+
X-KDE-Priority=100
X-KDE-Kerfuffle-APIRevision=1
X-KDE-Kerfuffle-ReadWrite=true
Name=lha archive plugin
Name[ca]=Connector per arxius LHA
Name[ca@valencia]=Connector per arxius LHA
Name[cs]=Modul pro archiv lha
Name[da]=Plugin til lha-arkiver
Name[de]=lha-Archiv-Modul
Name[es]=Complemento de archivo comprimido LHA
Name[et]=lha-arhiivi plugin
Name[eu]=lha artxibuen plugina
Name[fi]=lha-arkistointiliitännäinen
Name[fr]=Module d'archive lha
Name[ga]=Breiseán cartlainne lha
Name[hu]=lha modul
Name[ia]=plugin de archivar lha
Name[it]=plugin archivio lha
Name[kk]=lha архив плагині
Name[ko]=LHA 압축 플러그인
Name[lt]=lha archyvo priedas
Name[nb]=Programtillegg for lha-arkiv
Name[nds]=LHA-Archievmoduul
Name[nl]=lha-archiefplug-in
Name[pa]=lha ਅਕਾਇਵ ਪਲੱਗਇਨ
Name[pt]='Plugin' de pacotes LHA
Name[pt_BR]=Plug-in de arquivos LHA
Name[ro]=Modul de arhivă lha
Name[sk]=Modul lha archívu
Name[sr]=Прикључак ЛХА архива
Name[sr@ijekavian]=Прикључак ЛХА архива
Name[sr@ijekavianlatin]=Priključak LHA arhiva
Name[sr@latin]=Priključak LHA arhiva
Name[sv]=Insticksprogram för LHA-arkiv
Name[tr]=lha arşiv eklentisi
Name[uk]=Додаток для архівів LHA
Name[x-test]=xxlha archive pluginxx
Name[zh_CN]=lha 归档插件
Name[zh_TW]=lha 壓縮檔外掛程式
MimeType=@SUPPORTED_CLILHA_MIMETYPES@
