[Desktop Entry]
Type=Service
X-KDE-ServiceTypes=Kerfuffle/Plugin
X-KDE-Library=kerfuffle_clilha
X-KDE-PluginInfo-Author=Theofilos Intzoglou
X-KDE-PluginInfo-Email=int.teo@gmail.com
X-KDE-PluginInfo-Name=kerfuffle_clilha
X-KDE-PluginInfo-Version=0.0.1
X-KDE-PluginInfo-Website=http://www.kde.org
X-KDE-PluginInfo-License=GPLv2+
X-KDE-Priority=100
X-KDE-Kerfuffle-APIRevision=1
X-KDE-Kerfuffle-ReadWrite=true
Name=lha archive plugin
Name[ca]=Connector per arxius LHA
Name[cs]=Modul pro archiv lha
Name[de]=lha-Archiv-Modul
Name[es]=Complemento de archivo comprimido LHA
Name[eu]=lha artxibuen plugina
Name[hu]=lha modul
Name[lt]=lha archyvo priedas
Name[nb]=Programtillegg for lha-arkiv
Name[nds]=LHA-Archievmoduul
Name[nl]=lha-archiefplug-in
Name[pt]='Plugin' de pacotes LHA
Name[pt_BR]=Plug-in de arquivos LHA
Name[ro]=Modul de arhivă lha
Name[sk]=Modul lha archívu
Name[sv]=Insticksprogram för LHA-arkiv
Name[tr]=lha arşiv eklentisi
Name[uk]=Додаток для архівів LHA
Name[x-test]=xxlha archive pluginxx
Name[zh_TW]=lha 壓縮檔外掛程式
MimeType=@SUPPORTED_CLILHA_MIMETYPES@
