# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['Linux/Qt5', 'FreeBSD/Qt5']
  'require':
    'frameworks/extra-cmake-modules': '@stable'
    'frameworks/kcoreaddons': '@stable'
    'frameworks/kconfig': '@stable'
    'frameworks/ki18n': '@stable'
    'frameworks/karchive': '@stable'
    'frameworks/kcrash': '@stable'
    'frameworks/kdbusaddons': '@stable'
    'frameworks/kdoctools': '@stable'
    'frameworks/kitemmodels': '@stable'
    'frameworks/kio': '@stable'
    'frameworks/kservice': '@stable'
    'frameworks/kparts': '@stable'
    'frameworks/kpty': '@stable'
    'frameworks/kwidgetsaddons': '@stable'
    'frameworks/kiconthemes': '@stable'

- 'on': ['Linux/Qt6', 'FreeBSD/Qt6']
  'require':
    'frameworks/extra-cmake-modules': '@latest-kf6'
    'frameworks/kcoreaddons': '@latest-kf6'
    'frameworks/kconfig': '@latest-kf6'
    'frameworks/ki18n': '@latest-kf6'
    'frameworks/karchive': '@latest-kf6'
    'frameworks/kcrash': '@latest-kf6'
    'frameworks/kdbusaddons': '@latest-kf6'
    'frameworks/kdoctools': '@latest-kf6'
    'frameworks/kitemmodels': '@latest-kf6'
    'frameworks/kio': '@latest-kf6'
    'frameworks/kservice': '@latest-kf6'
    'frameworks/kparts': '@latest-kf6'
    'frameworks/kpty': '@latest-kf6'
    'frameworks/kwidgetsaddons': '@latest-kf6'
    'frameworks/kiconthemes': '@latest-kf6'

Options:
  require-passing-tests-on: [ 'Linux', 'FreeBSD' ]
