{
    "KPlugin": {
        "Description": "Open and extract DEB, RPM, ISO, AppImage, XAR, CAB, and EXE files",
        "Description[ar]": "يفتح ويستخرج ملفات DEB و RPM و ISO و AppImage و XAR و CAB و EXE",
        "Description[ast]": "Abre y estrae ficheros DEB, RPM, ISO, AppImage, XAR, CAB y EXE",
        "Description[bg]": "Отваряне и извличане на файлове DEB, RPM, ISO, AppImage, XAR, CAB и EXE",
        "Description[ca@valencia]": "Obri i extrau fitxers DEB, RPM, ISO, AppImage, XAR, CAB i EXE",
        "Description[ca]": "Obre i extreu fitxers DEB, RPM, ISO, AppImage, XAR, CAB i EXE",
        "Description[cs]": "Otevřít a rozbalit soubory DEB, RPM, ISO, AppImage, XAR, CAB a EXE",
        "Description[de]": "Öffnen und Entpacken von DEB-, RPM-, ISO-, AppImage-, XAR-, CAB- und EXE-Dateien",
        "Description[en_GB]": "Open and extract DEB, RPM, ISO, AppImage, XAR, CAB, and EXE files",
        "Description[eo]": "Malfermi kaj malpaki DEB, RPM, ISO, AppImage, XAR, CAB- kaj EXE-dosierojn",
        "Description[es]": "Abrir y extraer archivos DEB, RPM, ISO, AppImage, XAR, CAB y EXE",
        "Description[eu]": "Ireki eta erauzi DEB, RPM, ISO, AppImage, XAR, CAB, eta EXE fitxategiak",
        "Description[fr]": "Ouvrir et extraire les fichiers aux formats « DEB », « RPM », « ISO », « AppImage », « XAR », « CAB » et « EXE »",
        "Description[gl]": "Abrir e extraer ficheiros DEB, RPM, ISO, AppImage, XAR, CAB, e EXE.",
        "Description[he]": "פתיחה וחילוץ של קובצי DEB,‏ RPM,‏ ISO,‏ AppImage,‏ XAR,‏ CAB ו־EXE",
        "Description[hu]": "DEB-, RPM-, ISO-, AppImage-, XAR- CAB- és EXE-fájlok megnyitása és kibontása",
        "Description[ia]": "Aperir e Extraher files DEB, RPM, ISO, AppImage, XAR, CAB e EXE ",
        "Description[is]": "Opna og afþjappa DEB-, RPM-, ISO-, AppImage-, XAR-, CAB- og EXE-skrár",
        "Description[it]": "Apri ed estrai file DEB, RPM, ISO, AppImage, XAR e CAB e file EXE",
        "Description[ka]": "გახსენით და გაშალეთ DEB, RPM, ISO, AppImage, XAR, CAB და EXE ფაილები",
        "Description[ko]": "DEB, RPM, ISO, AppImage, XAR, CAB, EXE 파일 열고 풀기",
        "Description[lv]": "Atver un atspiež DEB, RPM, ISO, „AppImage“, XAR, CAB un EXE datnes",
        "Description[nl]": "Open en pak uit DEB, RPM, ISO, AppImage, XAR, CAB en EXE bestanden",
        "Description[nn]": "Opna og pakk ut DEB-, RPM-, ISO-, AppImage-, XAR-, CAB- og EXE-filer",
        "Description[pl]": "Otwiera i wypakowuje pliki DEB, RPM, ISO, AppImage, XAR, CAB oraz EXE",
        "Description[ro]": "Deschide și extrage fișiere DEB, RPM, ISO, AppImage, XAR. CAB și EXE",
        "Description[ru]": "Открытие и распаковка файлов DEB, RPM, ISO, AppImage, XAR, CAB и EXE",
        "Description[sl]": "Odpri in razširi datoteke DEB, RPM, ISO, AppImage, XAR in CAB in EXE",
        "Description[sv]": "Öppna och packa upp DEB-, RPM-, ISO-, AppImage-, XAR-, CAB- och EXE-filer",
        "Description[tr]": "DEB, RPM, ISO, AppImage, XAR ve CAB ve EXE dosyalarını açıp çıkarın",
        "Description[uk]": "Здатен відкривати і видобувати дані з архівів DEB, RPM, ISO, AppImage, XAR, CAB та EXE",
        "Description[x-test]": "xxOpen and extract DEB, RPM, ISO, AppImage, XAR, CAB, and EXE filesxx",
        "Description[zh_CN]": "打开和解压 DEB、RPM、ISO、AppImage、XAR、CAB 和 EXE 等文件类型",
        "Description[zh_TW]": "開啟並解壓縮 DEB、RPM、ISO、AppImage、XAR、CAB 或 EXE 檔案",
        "MimeTypes": [
            "application/x-deb",
            "application/x-cd-image",
            "application/x-bcpio",
            "application/x-cpio",
            "application/x-cpio-compressed",
            "application/x-sv4cpio",
            "application/x-sv4crc",
            "application/x-rpm",
            "application/x-compress",
            "application/gzip",
            "application/x-bzip",
            "application/x-bzip2",
            "application/x-lzma",
            "application/x-xz",
            "application/zlib",
            "application/zstd",
            "application/x-lz4",
            "application/x-lzip",
            "application/x-lrzip",
            "application/x-lzop",
            "application/x-source-rpm",
            "application/vnd.debian.binary-package",
            "application/vnd.efi.iso",
            "application/vnd.ms-cab-compressed",
            "application/x-xar",
            "application/x-iso9660-appimage",
            "application/x-archive",
            "application/x-msdownload"
        ],
        "Name": "Libarchive plugin (read-only formats)",
        "Name[ar]": "ملحق Libarchive (تنسيقات قراءة فقط)",
        "Name[ast]": "Plugin de libarchive (formatos de namás llectura)",
        "Name[az]": "Libarchive qoşması (yalnız_oxumaq formatları)",
        "Name[be]": "Убудова Libarchive (фарматы толькі для чытання)",
        "Name[bg]": "Приставка Libarchive (само за четене)",
        "Name[ca@valencia]": "Connector de Libarchive (formats de només lectura)",
        "Name[ca]": "Connector del Libarchive (formats de només lectura)",
        "Name[cs]": "Modul libarchive (formáty pouze pro čtení)",
        "Name[da]": "Libarchive-plugin (skrivebeskyttede formater)",
        "Name[de]": "LibArchive-Modul (Nur lesbare Formate)",
        "Name[el]": "Πρόσθετο Libarchive (ανάγνωση μόνο)",
        "Name[en_GB]": "Libarchive plugin (read-only formats)",
        "Name[eo]": "Libarchive-kromaĵo (nur-legaj formatoj)",
        "Name[es]": "Complemento Libarchive (formatos de solo lectura)",
        "Name[et]": "Libarchive'i plugin (kirjutuskaitstud vormingud)",
        "Name[eu]": "Libarchive plugina (irakurri-soilik formatuak)",
        "Name[fi]": "Libarchive-liitännäinen (vain luku -muodot)",
        "Name[fr]": "Module externe libarchive (formats en lecture seule)",
        "Name[gl]": "Complemento de libarchive (formatos de só lectura)",
        "Name[he]": "תוסף Libarchive (תסדירים לקריאה בלבד",
        "Name[hu]": "Libarchive bővítmény (csak olvasható formátumok)",
        "Name[ia]": "Libarchive plugin (formatos de sol lectura)",
        "Name[id]": "Plugin Libarchive (format hanya-baca)",
        "Name[ie]": "Plugin de Libarchive (formates solmen por letion)",
        "Name[is]": "Libarchive-viðbót (skrifvarin snið)",
        "Name[it]": "Estensione Libarchive (formati in sola lettura)",
        "Name[ja]": "Libarchive プラグイン (読み取り専用形式)",
        "Name[ka]": "Libarchive -ის მხარდაჭერა (მხოლოდ-კითხვისთვის)",
        "Name[ko]": "Libarchive 플러그인(읽기 전용 형식)",
        "Name[lv]": "„Libarchive“ spraudnis (tikai lasāmi formāti)",
        "Name[nl]": "LibArchive-plug-in (alleen-lezen formaten)",
        "Name[nn]": "Libarchive-tillegg (berre lesing)",
        "Name[pa]": "Libarchive ਪਲੱਗਇਨ (ਸਿਰਫ਼ ਪੜ੍ਹਨ ਲਈ ਫਾਰਮੈਟ)",
        "Name[pl]": "Wtyczka Libarchive (formaty tylko-do-odczytu)",
        "Name[pt]": "'Plugin' da Libarchive (formatos apenas para leitura)",
        "Name[pt_BR]": "Plugin Libarchive (formatos apenas para leitura)",
        "Name[ro]": "Extensie Libarchive (formate numai-citire)",
        "Name[ru]": "Модуль Libarchive (форматы только для чтения)",
        "Name[sk]": "Plugin Libarchive (formáty iba na čítanie)",
        "Name[sl]": "Vstavek Libarchive (samo za branje)",
        "Name[sr@ijekavian]": "Прикључак за Либархив (формати само‑за‑читање)",
        "Name[sr@ijekavianlatin]": "Priključak za libarchive (formati samo‑za‑čitanje)",
        "Name[sr@latin]": "Priključak za libarchive (formati samo‑za‑čitanje)",
        "Name[sr]": "Прикључак за Либархив (формати само‑за‑читање)",
        "Name[sv]": "Libarchive-insticksprogram (endast läsningsformat)",
        "Name[tr]": "Libarchive eklentisi (saltokunur biçimler)",
        "Name[uk]": "Додаток libarchive (формати лише для читання)",
        "Name[x-test]": "xxLibarchive plugin (read-only formats)xx",
        "Name[zh_CN]": "Libarchive 插件 (只读格式)",
        "Name[zh_TW]": "Libarchive 外掛程式（唯讀格式）",
        "Version": "@RELEASE_SERVICE_VERSION@"
    },
    "X-KDE-Kerfuffle-ReadWrite": false,
    "X-KDE-Priority": 100
}
