{
    "KPlugin": {
        "Description": "Open and extract single files compressed with the zstd algorithm",
        "Description[ar]": "يفتح و يستخرج الملفات المفردة المضغوطة باستخدام خوارزمية Zstd",
        "Description[az]": "Zstd alqoritmi ilə sıxılmış tək faylları açmaq və çıxartmaq",
        "Description[bg]": "Отваряне и извличане на единични файлове, компресирани с алгоритъм zstd",
        "Description[ca@valencia]": "Obri i extrau fitxers individuals comprimits amb l'algorisme «zstd»",
        "Description[ca]": "Obre i extreu fitxers individuals comprimits amb l'algorisme «zstd»",
        "Description[cs]": "Otevřít a rozbalit jednotlivé soubory komprimované algoritmem zstd",
        "Description[da]": "Åbn og udpak enkelte filer komprimeret med zstd-algoritmen",
        "Description[de]": "Öffnen und Entpacken von einzelnen mit dem zstd-Algorithmus komprimierten Dateien",
        "Description[el]": "Άνοιγμα και εξαγωγή απλών αρχείων συμπιεσμένα με τον αλγόριθμο zstd",
        "Description[en_GB]": "Open and extract single files compressed with the zstd algorithm",
        "Description[es]": "Abrir y extraer archivos individuales comprimidos con el algoritmo zstd",
        "Description[eu]": "Ireki eta erauzi zstd algoritmoarekin konprimatutako fitxategi bakunak",
        "Description[fi]": "Avaa ja pura Zstd-algoritmilla pakattuja yksittäistiedostoja",
        "Description[fr]": "Ouvrir et extraire des fichiers uniques compressés avec l'algorithme « zstd »",
        "Description[hu]": "A zstd algoritmussal tömörített fájlok megnyitása és kibontása",
        "Description[ia]": "Aperir e extraher singule files comprimite con le algorithmo zstd",
        "Description[id]": "Buka dan ekstrak file tunggal yang dikompresi dengan algoritma zstd",
        "Description[ie]": "Aperter e extraer singul files compresset per li algoritm zstd",
        "Description[is]": "Opna og afþjappa stakar skrár sem þajappað hefur verið með zstd-reikniriti",
        "Description[it]": "Apri ed estrai singoli file compressi con l'algoritmo zstd",
        "Description[ka]": "გახსენით და გაშალეთ zstd ფაილები",
        "Description[ko]": "zstd 알고리즘으로 압축된 단일 파일 열고 풀기",
        "Description[nl]": "Open en pak uit losse bestanden gecomprimeerd met het zstd-algoritme",
        "Description[nn]": "Opna og pakk ut einskildfiler komprimerte med zstd-algoritmen",
        "Description[pl]": "Otwiera i wypakowuje pojedyncze pliki spakowane algorytmem zstd",
        "Description[pt]": "Abrir e extrair ficheiros individuais comprimidos com o algoritmo ZSTD",
        "Description[pt_BR]": "Abrir e extrair arquivos individuais compactados com o algoritmo zstd",
        "Description[ro]": "Deschide și extrage fișiere singulare comprimate cu algoritmul zstd",
        "Description[ru]": "Открытие и распаковка отдельных файлов, сжатых по алгоритму zstd",
        "Description[sk]": "Otvorenie a extrahovanie jednotlivých súborov komprimovaných algoritmom zstd",
        "Description[sl]": "Odpri in razširi posamezne datoteke stisnjene z algoritmom zstd",
        "Description[sv]": "Öppna och packa upp enstaka filer komprimerade med zstd-algoritmen",
        "Description[ta]": "Zstd முறையில் சுருக்கப்பட்டுள்ள ஒற்றைக் கோப்பை திறக்கும், பிரித்தெடுக்கும்",
        "Description[tr]": "zstd algoritması ise sıkıştırılmış arşivleri açın ve çıkarın",
        "Description[uk]": "Здатен відкривати і видобувати дані із окремих файлів, стиснених за допомогою алгоритму zstd",
        "Description[x-test]": "xxOpen and extract single files compressed with the zstd algorithmxx",
        "Description[zh_CN]": "打开和解压 zstd 算法压缩的单个文件",
        "Description[zh_TW]": "開啟並解壓縮以 zstd 演算法壓縮的單一檔案",
        "Id": "kerfuffle_libzstd",
        "MimeTypes": [
            "@SUPPORTED_MIMETYPES@"
        ],
        "Name": "Zstd plugin",
        "Name[ar]": "ملحق Zstd",
        "Name[az]": "Zstd qoşması",
        "Name[bg]": "Приставка Zstd",
        "Name[ca@valencia]": "Connector de Zstd",
        "Name[ca]": "Connector del Zstd",
        "Name[cs]": "Modul pro zstd",
        "Name[da]": "Zstd-plugin",
        "Name[de]": "Zstd-Modul",
        "Name[el]": "Πρόσθετο zstd",
        "Name[en_GB]": "Zstd plugin",
        "Name[es]": "Complemento Zstd",
        "Name[eu]": "Zstd plugina",
        "Name[fi]": "Zstd-liitännäinen",
        "Name[fr]": "Module externe « Zstd »",
        "Name[hu]": "Zstd bővítmény",
        "Name[ia]": "Plugin de Zstd",
        "Name[id]": "Plugin Zstd",
        "Name[ie]": "Plugin Zstd",
        "Name[is]": "Zstd-viðbót",
        "Name[it]": "Estensione zstd",
        "Name[ka]": "Zstd -ის მხარდაჭერა",
        "Name[ko]": "Zstd 플러그인",
        "Name[nl]": "Zstd-plug-in",
        "Name[nn]": "Zstd-tillegg",
        "Name[pl]": "Wtyczka Zstd",
        "Name[pt]": "'Plugin' do Zstd",
        "Name[pt_BR]": "Plugin Zstd",
        "Name[ro]": "Extensie Zstd",
        "Name[ru]": "Модуль Zstd",
        "Name[sk]": "Zstd plugin",
        "Name[sl]": "Vstavek Zstd",
        "Name[sv]": "Zstd-insticksprogram",
        "Name[ta]": "Zstd செருகுநிரல்",
        "Name[tr]": "Zstd eklentisi",
        "Name[uk]": "Додаток zstd",
        "Name[x-test]": "xxZstd pluginxx",
        "Name[zh_CN]": "Zstd 插件",
        "Name[zh_TW]": "Zstd 外掛程式",
        "Version": "@RELEASE_SERVICE_VERSION@"
    },
    "X-KDE-Priority": 100
}
