[Desktop Entry]
Type=Service
ServiceTypes=KonqPopupMenu/Plugin
MimeType=@SUPPORTED_ARK_MIMETYPES@
Actions=arkAutoExtractHere;arkExtractTo;arkExtractHere;
X-KDE-Priority=TopLevel
X-KDE-StartupNotify=false
X-KDE-Submenu=Extract
X-KDE-Submenu[ar]=استخرِج
X-KDE-Submenu[ast]=Estrayer
X-KDE-Submenu[bg]=Извличане
X-KDE-Submenu[bs]=Raspakivanje
X-KDE-Submenu[ca]=Extreu
X-KDE-Submenu[ca@valencia]=Extreu
X-KDE-Submenu[cs]=Rozbalit
X-KDE-Submenu[da]=Pak ud
X-KDE-Submenu[de]=Entpacken
X-KDE-Submenu[el]=Εξαγωγή
X-KDE-Submenu[en_GB]=Extract
X-KDE-Submenu[es]=Extraer
X-KDE-Submenu[et]=Lahtipakkimine
X-KDE-Submenu[eu]=Atera
X-KDE-Submenu[fi]=Pura
X-KDE-Submenu[fr]=Extraire
X-KDE-Submenu[ga]=Bain amach
X-KDE-Submenu[gl]=Extraer
X-KDE-Submenu[hr]=Otpakiraj
X-KDE-Submenu[hu]=Kibontás
X-KDE-Submenu[ia]=Extrahe
X-KDE-Submenu[it]=Estrai
X-KDE-Submenu[ja]=展開
X-KDE-Submenu[kk]=Тарқату
X-KDE-Submenu[km]=ស្រង់ចេញ​
X-KDE-Submenu[ko]=압축 풀기
X-KDE-Submenu[lt]=Išpakuoti
X-KDE-Submenu[mr]=पुर्ववत करा
X-KDE-Submenu[nb]=Pakk ut
X-KDE-Submenu[nds]=Utpacken
X-KDE-Submenu[nl]=Uitpakken
X-KDE-Submenu[pa]=ਇੱਥੇ ਖਿਲਾਰੋ
X-KDE-Submenu[pl]=Wypakuj
X-KDE-Submenu[pt]=Extrair
X-KDE-Submenu[pt_BR]=Extrair
X-KDE-Submenu[ro]=Extrage
X-KDE-Submenu[ru]=Распаковать
X-KDE-Submenu[sk]=Rozbaliť
X-KDE-Submenu[sl]=Razširi
X-KDE-Submenu[sr]=Распакуј
X-KDE-Submenu[sr@ijekavian]=Распакуј
X-KDE-Submenu[sr@ijekavianlatin]=Raspakuj
X-KDE-Submenu[sr@latin]=Raspakuj
X-KDE-Submenu[sv]=Packa upp
X-KDE-Submenu[tr]=Çıkart
X-KDE-Submenu[ug]=ئايرىش
X-KDE-Submenu[uk]=Видобути
X-KDE-Submenu[x-test]=xxExtractxx
X-KDE-Submenu[zh_CN]=解压缩
X-KDE-Submenu[zh_TW]=解開

[Desktop Action arkExtractHere]
Name=Extract archive here
Name[ast]=Estrayer equí l'archivu
Name[ca]=Extreu l'arxiu aquí
Name[ca@valencia]=Extreu l'arxiu ací
Name[cs]=Rozbalit archiv sem
Name[de]=Archiv hierher auspacken
Name[en_GB]=Extract archive here
Name[es]=Extraer archivo comprimido aquí
Name[fi]=Pura paketti tähän
Name[fr]=Extraire l'archive ici
Name[gl]=Extraer o arquivo aquí
Name[it]=Estrai l'archivio qui
Name[ko]=여기에 압축 풀기
Name[nl]=Archief hier uitpakken
Name[pl]=Wypakuj archiwum tutaj
Name[pt]=Extrair o pacote para aqui
Name[pt_BR]=Extrair arquivo aqui
Name[sk]=Rozbaliť archív sem
Name[sl]=Razširi arhiv sem
Name[sr]=Распакуј архиву овде
Name[sr@ijekavian]=Распакуј архиву овдје
Name[sr@ijekavianlatin]=Raspakuj arhivu ovdje
Name[sr@latin]=Raspakuj arhivu ovde
Name[sv]=Packa upp arkiv här
Name[uk]=Видобути архів сюди
Name[x-test]=xxExtract archive herexx
Name[zh_TW]=在此解壓縮
Icon=ark
Exec=ark --batch --autodestination %F

[Desktop Action arkExtractTo]
Name=Extract archive to...
Name[ast]=Estrayer l'archivu en...
Name[ca]=Extreu l'arxiu a...
Name[ca@valencia]=Extreu l'arxiu a...
Name[cs]=Rozbalit archiv do...
Name[de]=Archiv auspacken nach ...
Name[en_GB]=Extract archive to...
Name[es]=Extraer archivo comprimido en...
Name[fi]=Pura paketti…
Name[fr]=Extraire l'archive vers...
Name[gl]=Extraer o arquivo en…
Name[it]=Estrai l'archivio in...
Name[ko]=다음 경로에 압축 풀기...
Name[nl]=Archief uitpakken naar...
Name[pl]=Wypakuj archiwum do...
Name[pt]=Extrair o pacote para...
Name[pt_BR]=Extrair arquivo para...
Name[sk]=Rozbaliť archív do...
Name[sl]=Razširi arhiv v ...
Name[sr]=Распакуј архиву у...
Name[sr@ijekavian]=Распакуј архиву у...
Name[sr@ijekavianlatin]=Raspakuj arhivu u...
Name[sr@latin]=Raspakuj arhivu u...
Name[sv]=Packa upp arkiv i...
Name[uk]=Видобути архів до…
Name[x-test]=xxExtract archive to...xx
Name[zh_TW]=解壓縮到...
Icon=ark
Exec=ark --batch --autodestination --dialog %F

[Desktop Action arkAutoExtractHere]
Name=Extract archive here, autodetect subfolder
Name[ast]=Estrayer equí l'archivu, autodeteutar socarpeta
Name[ca]=Extreu l'arxiu aquí, detecta automàticament la subcarpeta
Name[ca@valencia]=Extreu l'arxiu ací, detecta automàticament la subcarpeta
Name[cs]=Rozbalit archiv sem, automaticky detekovat podsložku
Name[de]=Archiv hierher auspacken, Unterordner selbständig ermitteln
Name[en_GB]=Extract archive here, autodetect subfolder
Name[es]=Extraer archivo comprimido aquí, autodetectar subcarpeta
Name[fi]=Pura paketti tähän, tunnista alikansio automaattisesti
Name[fr]=Extraire l'archive ici, auto-détecter les sous-dossiers
Name[gl]=Extraer o arquivo aquí, detectar o subcartafol
Name[it]=Estrai l'archivio qui, autorileva la sottocartella
Name[ko]=하위 폴더를 감지해서 여기에 압축 풀기
Name[nl]=Archief hier uitpakken, submap autodetecteren
Name[pl]=Wypakuj archiwum tutaj, wykryj podkatalogi
Name[pt]=Extrair o pacote aqui com detecção da sub-pasta
Name[pt_BR]=Extrair aqui detectando subpasta
Name[sk]=Rozbaliť archív sem, automaticky určiť podpriečinok
Name[sl]=Razširi arhiv sem, samodejno zaznaj podmapo
Name[sr]=Распакуј архиву овде, погоди потфасциклу
Name[sr@ijekavian]=Распакуј архиву овдје, погоди потфасциклу
Name[sr@ijekavianlatin]=Raspakuj arhivu ovdje, pogodi potfasciklu
Name[sr@latin]=Raspakuj arhivu ovde, pogodi potfasciklu
Name[sv]=Packa upp arkiv här, detektera underkatalog automatiskt
Name[uk]=Видобути архів сюди, автоматично визначити підтеку
Name[x-test]=xxExtract archive here, autodetect subfolderxx
Name[zh_TW]=在此解壓縮，自動偵測子資料夾
Icon=ark
Exec=ark --batch --autodestination --autosubfolder %F
