{
    "KPlugin": {
        "MimeTypes": [
            "@SUPPORTED_ARK_MIMETYPES_JSON@"
        ],
        "Name": "Ark Extract Here",
        "Name[ar]": "أرك استخرج هنا",
        "Name[ast]": "«Estrayer equí» d'Ark",
        "Name[az]": "Buraya çıxarın",
        "Name[be]": "Распакаваць сюды з дапамогай Ark",
        "Name[bg]": "Извличане с Ark тук",
        "Name[ca@valencia]": "Extracció d'Ark ací",
        "Name[ca]": "Extracció de l'Ark aquí",
        "Name[cs]": "Rozbalit Arkem sem",
        "Name[de]": "Ark hierher entpacken",
        "Name[el]": "Ark Εξαγωγή Εδώ",
        "Name[eo]": "Ark-Extrakti ĉi tie",
        "Name[es]": "Ark - Extraer aquí",
        "Name[eu]": "Ark Erauzi hemen",
        "Name[fi]": "Ark: pura tähän",
        "Name[fr]": "Extraire ici avec Ark",
        "Name[gl]": "Extraer aquí con Ark",
        "Name[he]": "חילוץ עם Ark לכאן",
        "Name[hu]": "Kibontás ide",
        "Name[ia]": "Ark Extrahe Hic",
        "Name[is]": "Ark afþjappa hingað",
        "Name[it]": "Ark estrai qui",
        "Name[ja]": "Ark で展開",
        "Name[ka]": "Ark აქ გაშლა",
        "Name[ko]": "Ark 여기에 압축 풀기",
        "Name[lv]": "„Ark“ izvilkt te",
        "Name[nl]": "Ark: hier uitpakken",
        "Name[nn]": "Pakk ut med Ark her",
        "Name[pa]": "ਆਕ ਇ਼ੱਥੇ ਖਿਲਾਰੋ",
        "Name[pl]": "Wypakuj tutaj",
        "Name[pt]": "Ark - Extrair Aqui",
        "Name[pt_BR]": "Extrair com o Ark aqui",
        "Name[ro]": "Ark extrage aici",
        "Name[ru]": "Распаковать в эту папку",
        "Name[sk]": "Extrahovať sem Arkom",
        "Name[sl]": "Arkov ekstrakt tukaj",
        "Name[sv]": "Ark packa upp här",
        "Name[tr]": "Ark Buraya Çıkar",
        "Name[uk]": "Розпакувати сюди за допомогою Ark",
        "Name[x-test]": "xxArk Extract Herexx",
        "Name[zh_CN]": "Ark 解压到此位置",
        "Name[zh_TW]": "Ark 在此解壓縮"
    }
}
