#ifndef LOGGING_ARK_H
#define LOGGING_ARK_H

#include <QLoggingCategory>

Q_DECLARE_LOGGING_CATEGORY(ARK)
Q_DECLARE_LOGGING_CATEGORY(KERFUFFLE)
Q_DECLARE_LOGGING_CATEGORY(KERFUFFLE_PLUGIN)
Q_DECLARE_LOGGING_CATEGORY(PART)

#endif /* LOGGING_ARK_H */