[Desktop Entry]
Type=Service
X-KDE-ServiceTypes=Kerfuffle/Plugin
X-KDE-Library=kerfuffle_cliunarchiver
X-KDE-PluginInfo-Author=Luke Shumaker
X-KDE-PluginInfo-Email=lukeshu@sbcglobal.net
X-KDE-PluginInfo-Name=kerfuffle_cliunarchiver
X-KDE-PluginInfo-Version=0.0.1
X-KDE-PluginInfo-Website=http://www.kde.org
X-KDE-PluginInfo-License=GPLv2+
X-KDE-Priority=100
X-KDE-Kerfuffle-APIRevision=1
X-KDE-Kerfuffle-ReadWrite=false
Name=The Unarchiver plugin
Name[ast]=El complementu desarchivador
Name[ca]=Connector del Unarchiver
Name[de]=Unarchiver-Modul
Name[nl]=De plug-in voor uit archief halen
Name[pl]=Wtyczka wypakowywacza
Name[pt]=O 'plugin' do Unarchiver
Name[pt_BR]=Plugin Unarchiver
Name[sr]=Прикључак Унархивера
Name[sr@ijekavian]=Прикључак Унархивера
Name[sr@ijekavianlatin]=Priključak Unarchivera
Name[sr@latin]=Priključak Unarchivera
Name[sv]=Insticksprogram för Unarchiver
Name[uk]=Додаток Unarchiver
Name[x-test]=xxThe Unarchiver pluginxx
MimeType=@SUPPORTED_CLIUNARCHIVER_MIMETYPES@
