{
    "KPlugin": {
        "Description": "Legacy support for the zip archive format",
        "Description[ar]": "دعم قديم لتنسيق أرشيف zip",
        "Description[ast]": "Compatibilidá heredada col formatu d'archivu ZIP",
        "Description[az]": "Zip arxivlərinin çıxarılmasının köhnə üsulu",
        "Description[be]": "Састарэлая падтрымка фармату zip",
        "Description[bg]": "Поддръжка на минали версии на архивен формат zip",
        "Description[ca@valencia]": "Implementació pel format d'arxiu «zip» antic",
        "Description[ca]": "Implementació pel format d'arxiu «zip» antic",
        "Description[cs]": "Historická podpora archivačního formátu zip",
        "Description[da]": "Understøttelse af det forældende zip-arkivformat",
        "Description[de]": "Unterstützung für veraltete Zip-Archivformate",
        "Description[el]": "Κληροδοτούμενη υποστήριξη για τον τύπο αρχειοθήκης zip",
        "Description[en_GB]": "Legacy support for the zip archive format",
        "Description[eo]": "Hereda subteno por la zip-arkivoformato",
        "Description[es]": "Uso heredado para el formato de archivo comprimido zip",
        "Description[et]": "Zip-arhiivi vormingu pärandtoetus",
        "Description[eu]": "zip artxibo formatuarentzako heredatutako euskarria",
        "Description[fi]": "Zip-tiedostomuodon perinteinen tuki",
        "Description[fr]": "Prise en charge traditionnelle du format d'archive zip",
        "Description[gl]": "Compatibilidade co formato de arquivo zip.",
        "Description[he]": "תמיכה בתסדיר ארכיוני zip מיושנים",
        "Description[hu]": "Elavult támogatás a zip archívumformátumhoz",
        "Description[ia]": "Supporto obsolescente per formato de archivo zip",
        "Description[id]": "Dukungan lama untuk format arsip zip",
        "Description[ie]": "Complet supporte por archives del formates zip",
        "Description[is]": "Stuðningur við eldri zip-safnskráasnið",
        "Description[it]": "Supporto originale per il formato di archivi ZIP",
        "Description[ja]": "zip アーカイブ形式のレガシーサポート",
        "Description[ka]": "Zip არქივის ფორმატის მოძველებული მხარდაჭერა",
        "Description[ko]": "zip 압축 형식의 레거시 지원",
        "Description[lv]": "Vecāku „zip“ formāta arhīvu atbalsts",
        "Description[nl]": "Verouderde ondersteuning voor het zip-archiefformaat",
        "Description[nn]": "Støtte for for det eldre arkivformatet ZIP",
        "Description[pa]": "ਜ਼ਿਪ ਅਕਾਇਵ ਫਾਰਮੈਟ ਲਈ ਪੁਰਾਣਾ ਸਹਿਯੋਗ",
        "Description[pl]": "Obsługa przestarzałego formatu archiwów zip",
        "Description[pt]": "Suporte antigo para o formato de pacotes ZIP",
        "Description[pt_BR]": "Suporte antigo para o formato de arquivo ZIP",
        "Description[ro]": "Suport moștenit pentru formatul de arhivă zip",
        "Description[ru]": "Старый способ поддержки архивов ZIP",
        "Description[sk]": "Spätná podpora pre archívny formát zip",
        "Description[sl]": "Opuščena podpora za arhive vrste zip",
        "Description[sr@ijekavian]": "Подршка за застареле архиве формата ЗИП",
        "Description[sr@ijekavianlatin]": "Podrška za zastarele arhive formata ZIP",
        "Description[sr@latin]": "Podrška za zastarele arhive formata ZIP",
        "Description[sr]": "Подршка за застареле архиве формата ЗИП",
        "Description[sv]": "Stöd för föråldrat zip-arkivformat",
        "Description[tr]": "Zip arşivi biçimi için eski desteği",
        "Description[uk]": "Підтримка архівів у застарілій версії формату zip",
        "Description[x-test]": "xxLegacy support for the zip archive formatxx",
        "Description[zh_CN]": "支持旧式 ZIP 压缩文件格式",
        "Description[zh_TW]": "對 zip 壓縮格式的舊版支援",
        "MimeTypes": [
            "application/x-java-archive",
            "application/zip"
        ],
        "Name": "Info-zip plugin",
        "Name[ar]": "ملحق Info-zip",
        "Name[ast]": "Plugin d'info-zip",
        "Name[az]": "İnfo-zip qoşması",
        "Name[be]": "Убудова Info-zip",
        "Name[bg]": "Приставка Info-zip",
        "Name[ca@valencia]": "Connector d'Info-zip",
        "Name[ca]": "Connector de l'Info-zip",
        "Name[cs]": "Modul info-zip",
        "Name[da]": "Info-zip-plugin",
        "Name[de]": "Info-zip-Modul",
        "Name[el]": "Πρόσθετο Info-zip",
        "Name[en_GB]": "Info-zip plugin",
        "Name[eo]": "Info-zip kromprogramo",
        "Name[es]": "Complemento Info-zip",
        "Name[et]": "Info-zipi plugin",
        "Name[eu]": "Info-zip plugina",
        "Name[fi]": "Info-Zip-liitännäinen",
        "Name[fr]": "Module externe info-zip",
        "Name[gl]": "Complemento de info-zip",
        "Name[he]": "תוסף פרטי Zip",
        "Name[hu]": "Info-zip bővítmény",
        "Name[ia]": "Info-zip plugin",
        "Name[id]": "Plugin info-zip",
        "Name[ie]": "Plufin Info-zip",
        "Name[is]": "Info-zip viðbót",
        "Name[it]": "Estensione Info-zip",
        "Name[ja]": "Info-zip プラグイン",
        "Name[ka]": "Info-zip -ის მხარდაჭერა",
        "Name[ko]": "Info-zip 플러그인",
        "Name[lv]": "„Info-zip“ spraudnis",
        "Name[nl]": "Info-zip-plug-in",
        "Name[nn]": "Info-ZIP-tillegg",
        "Name[pa]": "Info-zip ਪਲੱਗਇਨ",
        "Name[pl]": "Wtyczka info-zip",
        "Name[pt]": "'Plugin' do Info-zip",
        "Name[pt_BR]": "Plugin Info-zip",
        "Name[ro]": "Extensie Info zip",
        "Name[ru]": "Модуль Info-zip",
        "Name[sk]": "Plugin Info-zip",
        "Name[sl]": "Vstavek Info-zip",
        "Name[sr@ijekavian]": "Прикључак за Инфозип",
        "Name[sr@ijekavianlatin]": "Priključak za Info‑ZIP",
        "Name[sr@latin]": "Priključak za Info‑ZIP",
        "Name[sr]": "Прикључак за Инфозип",
        "Name[sv]": "Info-zip-insticksprogram",
        "Name[tr]": "Info-zip eklentisi",
        "Name[uk]": "Додаток info-zip",
        "Name[x-test]": "xxInfo-zip pluginxx",
        "Name[zh_CN]": "Info-zip 插件",
        "Name[zh_TW]": "Info-zip 外掛程式",
        "Version": "@RELEASE_SERVICE_VERSION@"
    },
    "X-KDE-Kerfuffle-ReadOnlyExecutables": [
        "zipinfo",
        "unzip"
    ],
    "X-KDE-Kerfuffle-ReadWrite": true,
    "X-KDE-Kerfuffle-ReadWriteExecutables": [
        "zip"
    ],
    "X-KDE-Priority": 160,
    "application/x-java-archive": {
        "CompressionLevelDefault": 6,
        "CompressionLevelMax": 9,
        "CompressionLevelMin": 0,
        "Encryption": true,
        "SupportsTesting": true
    },
    "application/zip": {
        "CompressionLevelDefault": 6,
        "CompressionLevelMax": 9,
        "CompressionLevelMin": 0,
        "CompressionMethodDefault": "Deflate",
        "CompressionMethods": {
            "BZip2": "bzip2",
            "Deflate": "deflate",
            "Store": "store"
        },
        "Encryption": true,
        "EncryptionMethodDefault": "ZipCrypto",
        "EncryptionMethods": [
            "ZipCrypto"
        ],
        "SupportsTesting": true
    }
}
